version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=belajar
    ports:
      - '3307:3306'
    networks:
      - mysql_network
  app:
    container_name: rest-template
    image: rest-template:latest
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
     - '8888:8080'
    networks:
      - mysql_network
    environment:
      - MYSQL_ADDRESS=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=belajar
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
networks:
  mysql_network:
    name: mysql_network
